export const audioMap = {
  "Welcome to Multiplication as Repeated Addition!": "/assets/audio/multiplication/mult_welcome_to_multiplication_as_repeated_addition__0.mp3",
  "Today, we are going to discover that multiplication is just a clever shortcut for adding the same number again and again.": "/assets/audio/multiplication/mult_today__we_are_going_to_discover_that_multiplicatio_1.mp3",
  "Have you ever wondered if there is a faster way to add the same number many times?": "/assets/audio/multiplication/mult_have_you_ever_wondered_if_there_is_a_faster_way_to_2.mp3",
  "Get ready to explore equal groups, build multiplication sentences, and solve fun challenges! Let's begin our adventure!": "/assets/audio/multiplication/mult_get_ready_to_explore_equal_groups__build_multiplic_3.mp3",
  "If every basket has the same number of apples, is there a faster way to find the total without adding one by one?": "/assets/audio/multiplication/mult_if_every_basket_has_the_same_number_of_apples__is__4.mp3",
  "Equal groups hold a secret — can you figure it out?": "/assets/audio/multiplication/mult_equal_groups_hold_a_secret___can_you_figure_it_out_5.mp3",
  "What if we had three plates, each with four dumplings? Adding them one by one takes a while... but what if there was a shortcut?": "/assets/audio/multiplication/mult_what_if_we_had_three_plates__each_with_four_dumpli_6.mp3",
  "Multiplication is that shortcut — and you are about to discover it!": "/assets/audio/multiplication/mult_multiplication_is_that_shortcut___and_you_are_abou_7.mp3",
  "Imagine rows of seats at a school event. Every row has the same number of chairs. How do we count them all quickly?": "/assets/audio/multiplication/mult_imagine_rows_of_seats_at_a_school_event__every_row_8.mp3",
  "Equal groups are everywhere — once you see them, you cannot un-see them!": "/assets/audio/multiplication/mult_equal_groups_are_everywhere___once_you_see_them__y_9.mp3",
  "What if I told you that adding the same number over and over has a secret name?": "/assets/audio/multiplication/mult_what_if_i_told_you_that_adding_the_same_number_ove_10.mp3",
  "That secret name is multiplication, and today you will unlock it!": "/assets/audio/multiplication/mult_that_secret_name_is_multiplication__and_today_you__11.mp3",
  "How many pencils are there if every pack has the same number?": "/assets/audio/multiplication/mult_how_many_pencils_are_there_if_every_pack_has_the_s_12.mp3",
  "Counting equal groups is the key to multiplication!": "/assets/audio/multiplication/mult_counting_equal_groups_is_the_key_to_multiplication_13.mp3",
  "Alice is setting up her stall at the school fair. She arranges her packs of stickers in equal rows.": "/assets/audio/multiplication/mult_alice_is_setting_up_her_stall_at_the_school_fair___14.mp3",
  "Each pack has the same number of stickers. Alice wonders how many stickers she has altogether.": "/assets/audio/multiplication/mult_each_pack_has_the_same_number_of_stickers__alice_w_15.mp3",
  "Let's help Alice count her stickers!": "/assets/audio/multiplication/mult_let_s_help_alice_count_her_stickers__16.mp3",
  "Instead of counting one by one, Alice groups them equally — that means every group has exactly the same number inside.": "/assets/audio/multiplication/mult_instead_of_counting_one_by_one__alice_groups_them__17.mp3",
  "Equal groups means every group has the same number inside.": "/assets/audio/multiplication/mult_equal_groups_means_every_group_has_the_same_number_18.mp3",
  "When we add the same number again and again, we call it repeated addition.": "/assets/audio/multiplication/mult_when_we_add_the_same_number_again_and_again__we_ca_19.mp3",
  "Repeated addition is adding the same number over and over.": "/assets/audio/multiplication/mult_repeated_addition_is_adding_the_same_number_over_a_20.mp3",
  "Alice has three packs, each with four stickers. So she writes: four plus four plus four equals twelve!": "/assets/audio/multiplication/mult_alice_has_three_packs__each_with_four_stickers__so_21.mp3",
  "But writing the same number so many times is slow. There is a faster way — using the multiplication symbol!": "/assets/audio/multiplication/mult_but_writing_the_same_number_so_many_times_is_slow__22.mp3",
  "The times symbol is our shortcut sign. It means groups of.": "/assets/audio/multiplication/mult_the_times_symbol_is_our_shortcut_sign__it_means_gr_23.mp3",
  "Four times three means four, three times. It is the same as four plus four plus four!": "/assets/audio/multiplication/mult_four_times_three_means_four__three_times__it_is_th_24.mp3",
  "So repeated addition and multiplication sentences always give the same answer.": "/assets/audio/multiplication/mult_so_repeated_addition_and_multiplication_sentences__25.mp3",
  "Alice is so happy! She can now write a multiplication sentence for any equal group she sees.": "/assets/audio/multiplication/mult_alice_is_so_happy__she_can_now_write_a_multiplicat_26.mp3",
  "Let's see if we can do it too!": "/assets/audio/multiplication/mult_let_s_see_if_we_can_do_it_too__27.mp3",
  "Tap each group to build your equal groups, and watch the addition sentence grow!": "/assets/audio/multiplication/mult_tap_each_group_to_build_your_equal_groups__and_wat_28.mp3",
  "Every time you add a group, the total goes up by the same amount. Do you see the pattern?": "/assets/audio/multiplication/mult_every_time_you_add_a_group__the_total_goes_up_by_t_29.mp3",
  "Now look at the repeated addition sentence on screen. Can you turn it into a multiplication sentence?": "/assets/audio/multiplication/mult_now_look_at_the_repeated_addition_sentence_on_scre_30.mp3",
  "The number of groups tells us how many times we add. The group size is the number we keep adding.": "/assets/audio/multiplication/mult_the_number_of_groups_tells_us_how_many_times_we_ad_31.mp3",
  "Look at the groups on screen and tell me how many there are in all.": "/assets/audio/multiplication/mult_look_at_the_groups_on_screen_and_tell_me_how_many__32.mp3",
  "Look at this real-world scene. Count the equal groups and find the total!": "/assets/audio/multiplication/mult_look_at_this_real_world_scene__count_the_equal_gro_33.mp3",
  "You can see equal groups all around us — at the hawker centre, the playground, and even the classroom!": "/assets/audio/multiplication/mult_you_can_see_equal_groups_all_around_us___at_the_ha_34.mp3",
  "Amazing! You built the groups and found the total. Well done!": "/assets/audio/multiplication/mult_amazing__you_built_the_groups_and_found_the_total__35.mp3",
  "Fantastic! You matched the sentence perfectly!": "/assets/audio/multiplication/mult_fantastic__you_matched_the_sentence_perfectly__36.mp3",
  "Brilliant! You found the total from the real-world scene!": "/assets/audio/multiplication/mult_brilliant__you_found_the_total_from_the_real_world_37.mp3",
  "What did we learn today about equal groups and multiplication?": "/assets/audio/multiplication/mult_what_did_we_learn_today_about_equal_groups_and_mul_38.mp3",
  "How confident do you feel about writing multiplication sentences from equal groups?": "/assets/audio/multiplication/mult_how_confident_do_you_feel_about_writing_multiplica_39.mp3",
  "Let's review the key ideas one more time.": "/assets/audio/multiplication/mult_let_s_review_the_key_ideas_one_more_time__40.mp3",
  "Look at the equal groups on screen. Write the repeated addition sentence.": "/assets/audio/multiplication/mult_look_at_the_equal_groups_on_screen__write_the_repe_41.mp3",
  "Look at the repeated addition sentence on screen. Choose the matching multiplication sentence.": "/assets/audio/multiplication/mult_look_at_the_repeated_addition_sentence_on_screen___42.mp3",
  "Look at the multiplication sentence on screen. Work out the total by counting the equal groups.": "/assets/audio/multiplication/mult_look_at_the_multiplication_sentence_on_screen__wor_43.mp3",
  "Look at the multiplication sentence on screen. Write the matching repeated addition sentence.": "/assets/audio/multiplication/mult_look_at_the_multiplication_sentence_on_screen__wri_44.mp3",
  "Listen to the story problem. Find the total by identifying the equal groups.": "/assets/audio/multiplication/mult_listen_to_the_story_problem__find_the_total_by_ide_45.mp3",
  "Look at the groups of objects on screen. Choose the multiplication sentence that matches.": "/assets/audio/multiplication/mult_look_at_the_groups_of_objects_on_screen__choose_th_46.mp3",
  "You got it! That is exactly right!": "/assets/audio/multiplication/mult_you_got_it__that_is_exactly_right__47.mp3",
  "Wonderful! You are a multiplication superstar!": "/assets/audio/multiplication/mult_wonderful__you_are_a_multiplication_superstar__48.mp3",
  "Fantastic work! Keep that streak going!": "/assets/audio/multiplication/mult_fantastic_work__keep_that_streak_going__49.mp3",
  "Super! You found the equal groups perfectly!": "/assets/audio/multiplication/mult_super__you_found_the_equal_groups_perfectly__50.mp3",
  "Not quite — but great thinking! Let us count the groups one more time, slowly.": "/assets/audio/multiplication/mult_not_quite___but_great_thinking__let_us_count_the_g_51.mp3",
  "Hmm, let us look at this again together. How many groups do we have?": "/assets/audio/multiplication/mult_hmm__let_us_look_at_this_again_together__how_many__52.mp3",
  "Almost! Remember, the number we keep adding is the group size.": "/assets/audio/multiplication/mult_almost__remember__the_number_we_keep_adding_is_the_53.mp3",
  "Good try! Count each group carefully and then add them all up.": "/assets/audio/multiplication/mult_good_try__count_each_group_carefully_and_then_add__54.mp3",
  "At the school canteen, each tray has the same number of curry puffs. Count the trays and find the total!": "/assets/audio/multiplication/mult_at_the_school_canteen__each_tray_has_the_same_numb_55.mp3",
  "At the hawker centre, there are rows of chairs with the same number in each row. How many chairs are there altogether?": "/assets/audio/multiplication/mult_at_the_hawker_centre__there_are_rows_of_chairs_wit_56.mp3",
  "On the MRT, each carriage has the same number of seats. Count the carriages to find the total seats!": "/assets/audio/multiplication/mult_on_the_mrt__each_carriage_has_the_same_number_of_s_57.mp3",
  "At the void deck, children arranged their toys in equal piles. Count the piles to find how many toys there are in all.": "/assets/audio/multiplication/mult_at_the_void_deck__children_arranged_their_toys_in__58.mp3",
  "At the provision shop, drinks are packed in equal rows. How many drinks are there in total?": "/assets/audio/multiplication/mult_at_the_provision_shop__drinks_are_packed_in_equal__59.mp3",
  "You completed the Multiplication as Repeated Addition adventure!": "/assets/audio/multiplication/mult_you_completed_the_multiplication_as_repeated_addit_60.mp3",
  "You have discovered that equal groups, repeated addition, and multiplication sentences all tell the same story — just in different ways.": "/assets/audio/multiplication/mult_you_have_discovered_that_equal_groups__repeated_ad_61.mp3",
  "You are now a multiplication explorer!": "/assets/audio/multiplication/mult_you_are_now_a_multiplication_explorer__62.mp3",
  "Welcome to Sticker Street!": "/assets/audio/multiplication/mult_welcome_to_sticker_street__63.mp3",
  "Welcome to Apple Orchard!": "/assets/audio/multiplication/mult_welcome_to_apple_orchard__64.mp3",
  "Welcome to Ocean Market!": "/assets/audio/multiplication/mult_welcome_to_ocean_market__65.mp3",
  "Welcome to Sky Carnival!": "/assets/audio/multiplication/mult_welcome_to_sky_carnival__66.mp3",
  "Welcome to Hawker Haven!": "/assets/audio/multiplication/mult_welcome_to_hawker_haven__67.mp3",
  "Welcome to Rocket Launch!": "/assets/audio/multiplication/mult_welcome_to_rocket_launch__68.mp3",
  "Welcome to Dragon Cave!": "/assets/audio/multiplication/mult_welcome_to_dragon_cave__69.mp3",
  "Welcome to Crystal Tower!": "/assets/audio/multiplication/mult_welcome_to_crystal_tower__70.mp3",
  "Welcome to Rainbow Bridge!": "/assets/audio/multiplication/mult_welcome_to_rainbow_bridge__71.mp3",
  "Welcome to Number Palace!": "/assets/audio/multiplication/mult_welcome_to_number_palace__72.mp3"
};
